
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoszteraenrdkpsfhgne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvc3p0ZXJhZW5yZGtwc2ZoZ25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTA4OTEsImV4cCI6MjA2MTU4Njg5MX0.IbM_q7IK6BbIzIqy5vLD-qcUbEyqipNfXiQUW58ilYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
